import type { Metadata } from "next";
import "./globals.css";
import { ConfirmProvider } from "@/components/ui/ConfirmDialog";
import { ToastProvider, ToastContainer } from "@/components/ui/Toast";
import { ThemeProvider } from "@/components/ThemeProvider";
import { geistSans, geistMono } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "GladPros",
  description: "Generated by GladPros App",
  icons: {
    icon: "/icon.ico",
    shortcut: "/icon.ico",
    apple: "/images/LOGO_300.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <ConfirmProvider>
            <ToastProvider>
              {children}
              <ToastContainer />
            </ToastProvider>
          </ConfirmProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
