name: CI

on:
  push:
    branches: [ main, chore/refactor-structure ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx eslint . --max-warnings=0
      - name: Typecheck
        run: npx tsc --noEmit
      - name: Run tests
        run: npm test --silent
      - name: Build
        run: npm run build --if-present
        env:
          # Use environment secrets if available, otherwise use temporary build values
          JWT_SECRET: ${{ secrets.JWT_SECRET || 'temporary-jwt-secret-for-build-only-32-chars' }}
          CLIENT_DOC_ENCRYPTION_KEY_BASE64: ${{ secrets.CLIENT_DOC_ENCRYPTION_KEY_BASE64 || 'dGVtcG9yYXJ5LWVuY3J5cHRpb24ta2V5LWZvci1idWlsZA==' }}
          CLIENT_DOC_ENCRYPTION_KEY_FALLBACKS: ${{ secrets.CLIENT_DOC_ENCRYPTION_KEY_FALLBACKS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL || 'mysql://user:pass@localhost:3306/temp_build_db' }}
          NEXT_PHASE: 'phase-production-build'
