name: CI

on:
  push:
    branches: [ main, chore/**, ci/**, chore/*, archive/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint -- --max-warnings=0
      - name: Typecheck
        run: npx tsc --noEmit
      - name: Test
        run: npm test --silent
      - name: Build
        run: npm run build --if-present
