name: Smoke E2E

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Start server
        run: nohup npm start & sleep 5
      - name: Run smoke tests
        run: bash ./scripts/smoke-test.sh
